import Detect from "@/components/detect";
import { setRequestLocale } from "next-intl/server";
import { Metadata } from "next";

export async function generateMetadata(): Promise<Metadata> {
  return {
    title: "AI Image Detector - Detect AI Generated Images | Detect AI",
    description: "Upload and analyze images to detect if they were generated by AI. Fast, accurate, and secure image detection service with confidence scores.",
    keywords: "AI image detector, AI generated images, deepfake detection, fake image detection, artificial intelligence",
  };
}

export default async function DetectPage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  setRequestLocale(locale);

  return <Detect />;
}
